version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "nemeth"
      POSTGRES_USER: "nemeth-legtechnika"
      POSTGRES_PASSWORD: "nemeth-legtechnika"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: