version: '3.9'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DOCKER_PRODUCT_SERVICE_URL: ${DOCKER_PRODUCT_SERVICE_URL}
      DOCKER_ORDER_SERVICE_URL: ${DOCKER_ORDER_SERVICE_URL}
    ports:
      - "9000:9000"

  order-service:
    build: ./orders
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DOCKER_MONGODB_URL: ${DOCKER_MONGODB_URL}
      DOCKER_PRODUCT_SERVICE_URL: ${DOCKER_PRODUCT_SERVICE_URL}
      DOCKER_KEYCLOAK_BASE_URL: ${DOCKER_KEYCLOAK_BASE_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      DOCKER_JWK_SET_URI: ${DOCKER_JWK_SET_URI}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - api-gateway
      - mongodb
      - keycloak

  product-service:
    build: ./products
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DOCKER_DB_URL: ${DOCKER_DB_URL}
      DOCKER_JWK_SET_URI: ${DOCKER_JWK_SET_URI}
    ports:
      - "8080:8080"
    depends_on:
      - api-gateway
      - postgres
      - keycloak

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run/postgresql
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.1
    container_name: keycloak
    command: [ "start-dev", "--import-realm" ]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - postgres

volumes:
  db_data:
  mongodb_data: