version: '3.9'

services:
  web:
    build: ./products
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "nemeth"
      POSTGRES_USER: "nemeth-legtechnika"
      POSTGRES_PASSWORD: "nemeth-legtechnika"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run/postgresql
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: