server:
  port: 8080

spring:
  config:
    activate:
      on-profile: docker
  banner:
    location: "classpath:/banner/banner.txt"
  datasource:
    url: ${DOCKER_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    url: ${spring.datasource.url}
    driverClassName: org.postgresql.Driver
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    changeLog: "classpath:db/changelog/changelog-master.yaml"
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${DOCKER_JWK_SET_URI}
  logging:
    level:
      root: trace

api:
  key:
    value: ${API_KEY}
    header: X-API-KEY
