server:
  port: 8081

spring:
  config:
    activate:
      on-profile: docker
  banner:
    location: "classpath:/banner/banner.txt"
  data:
    mongodb:
      uri: ${DOCKER_MONGODB_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${DOCKER_JWK_SET_URI}

service:
  product:
    url: ${DOCKER_PRODUCT_SERVICE_URL}
  keycloak:
    url: ${DOCKER_KEYCLOAK_BASE_URL}
    realm: ${KEYCLOAK_REALM}
    client-id: ${KEYCLOAK_CLIENT_ID}
    client-secret: ${KEYCLOAK_CLIENT_SECRET}