name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with coverage
        run: ./gradlew koverXmlReport

      - name: Publish Test Results
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: JUnit Tests
          path: '**products/build/test-results/test/TEST-*.xml'
          reporter: java-junit
          fail-on-error: false

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: products/build/reports/tests

      - name: JaCoCo Code Coverage Report
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ./products/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 10
          min-coverage-changed-files: 15
          update-comment: 'true'
          title: 'Code Coverage'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: code-coverage
          recreate: true
          path: code-coverage-results.md